use_frameworks!

platform :ios, '10.0'

target 'BXKAdvertSDK_Example' do
  pod 'BXKAdvertSDK', :path => '../'

  target 'BXKAdvertSDK_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
